### PR TITLE
docs: add JworkzAnimJImportFixMod v1.0.0 info

### PR DESCRIPTION
**Pull request by stiefeljackal**
Add the required information for the AnimJ Import Fix mod (JworkzAnimJImportFixMod).

### CODE REVIEW

**Review by EIA485 — APPROVED** [review]
built in debug mode

**Comment by stiefeljackal** [comment]
@EIA485 This was built in Release mode. I rechecked the produced SHA256 hash between Release and Debug and found them to be the following:

Debug: B9FB0D55DC586C77EFDE1118EF3C79E6E0D3D60ECC96FF5569E293BFCB064291
Release: 71E8A0ACFBCF235BC0AAFE1F161C9DA3E486DE0C2E1EF046730629FCBA735686

Where is it showing up as Debug? Thanks!

**Comment by stiefeljackal** [comment]
According to [C# Debug vs. Release Builds and Debugging in Visual Studio – from Novice to Expert in One Blog Article](https://www.codeproject.com/Articles/1239524/Csharp-Debug-vs-Release-Builds-and-Debugging-in-Vi), this attribute with this passed enum is standard for Release mode. Additionally, previously approved mods that I checked contain the following as well:

``` 	
.custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) = (
    01 00 02 00 00 00 00 00
)
```

**Comment by XDelta** [comment]
> 71E8A0ACFBCF235BC0AAFE1F161C9DA3E486DE0C2E1EF046730629FCBA735686 has the attribute [assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)] i may have miss understood it's meaning

Yeah that is normal for a Release Build.
If it was built in Debug, you'll see something more along the lines of:

> [assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]

**Pull request merged**
