### PR TITLE
Add manifest flag for android platforms

### PR DESCRIPTION
**Pull request by Raemien**
This change extends the platform compatibility flags to include android.

Useful for purposes mentioned in #235, where mods may require Android/Quest-specific features.

### CODE REVIEW

**Review by EIA485 — APPROVED** [review]
seems good to me.

**Comment by EIA485** [comment]
Since this is a change to the schema I'd like a second opinion before merging

**Comment by EIA485** [comment]
mobile app is weird, trying to request a review.

**Comment by XDelta** [comment]
Looks good to me, only additional consideration would be to bump the patch number on the schema version in the manifest (x.x.1) as it is changing the schema and its validation.

**Comment by XDelta** [comment]
Adding this along with some other things on the docs at the moment

**Pull request merged**
