### PR TITLE
Update IkCulling to 1.4.0

### PR DESCRIPTION
**Pull request by KyuubiYoru**

### CODE REVIEW

**Comment by EIA485** [comment]
can you add the new version instead of replacing the old one?

**Comment by zkxs** [comment]
```cs
if (Config.GetValue(AutoSaveConfig) || Equals(configurationChangedEvent?.Key, AutoSaveConfig))
    Config.Save(true);
```

Just FYI, this will cause a config save to disk every time someone types a character into any of the NeosModSettings fields, which can be quite spammy. In the current version of NML the save is done from the calling thread, which in your case is Unity's main thread, so this *could* cause the game to stutter (but in my testing it's not noticeable).

Meanwhile, I'm working on a NML change to detect config.Save() spam like this as well as moving the config file saving into a background thread, so mods doing stuff like this in the future will be safe to ignore (although still not good practice).

**Review by ljoonal — CHANGES_REQUESTED** [review]
The mod list should be mostly append only. I can only imagine a few very special cases where entries would be entirely removed from the list.

**Comment by ljoonal** [comment]
@KyuubiYoru if you could instead of overwriting the new version just add a new one, then this could be merged, otherwise this issue shall be closed if there's no further activity in a while.

**Pull request closed without merging**
