### PR TITLE
fix GifImporter

### LINKED ISSUE #184: GifImporter requires a update
Look's like @kawaiiamber has changed their github username to @astralchan. All the links need to changed.

https://github.com/neos-modding-group/neos-mod-manifest/blob/dbeef499b4b8ece52e2db54ca79943f19b30894d/manifest.json#L2726-L2758

### PR DESCRIPTION
**Pull request by hazre**
closes #184

### CODE REVIEW

**Comment by EIA485** [comment]
no hashes changed. seems fine to me

**Review by XDelta — APPROVED** [review]
My one reservation was "tk.kawaiiamber.gifimporter" to "tk.astralchan.gifimporter" would not match any releases of the mod. Probably fine though

**Comment by XDelta** [comment]
I did open an issue for that and other mod info fields

**Comment by EIA485** [comment]
seems fine since we never guaranteed harmony ids to match manifest ids, many mods just used the same id

**Pull request merged**
