### PR TITLE
add StackTraceFixer

### PR DESCRIPTION
**Pull request by art0007i**

### CODE REVIEW

**Review by EIA485 — DISMISSED** [review]

**Review by ljoonal — DISMISSED** [review]
Non-blocking notes:

- AssemblyCompany is empty, would be nice to see author names there :)
- It's a bit weird that a mod that reduces logs logs an unconditional warning at startup. To me it seems like a Msg or Debug would be more approriate?

**Comment by EIA485** [comment]
> Non-blocking notes:
> 
>     * AssemblyCompany is empty, would be nice to see author names there :)
> 
>     * It's a bit weird that a mod that reduces logs logs an unconditional warning at startup. To me it seems like a Msg or Debug would be more approriate?

am i blind?
i dont see any warning at startup in the source or disassembled binary,
just some debug logs while patching each method

**Comment by ljoonal** [comment]
>  i dont see any warning at startup in the source or disassembled binary,

Disassembled IL snippet from OnEngineInit:
```cil
IL_0021: ldstr "FrooxEngine.LogiX.LogixHelper+<EnumerateAllReachableNodes>d__17"
IL_0026: call class [mscorlib]System.Type ['0Harmony']HarmonyLib.AccessTools::TypeByName(string)
IL_002b: call void [NeosModLoader]NeosModLoader.NeosMod::Warn(object)
```
which translates to
```csharp
NeosMod.Warn(AccessTools.TypeByName("FrooxEngine.LogiX.LogixHelper+<EnumerateAllReachableNodes>d__17"));
```

**Comment by art0007i** [comment]
really weird, for some reason the build button in visual studio wasn't working but after a clean it works now, I'm gonna replace the binary with the correct one

**Review by EIA485 — APPROVED** [review]

**Comment by ljoonal** [comment]
>  Also what is what is AssemblyCompany?

https://github.com/art0007i/StackTraceFixer/blob/master/StackTraceFixer/Properties/AssemblyInfo.cs#L10=

Microsoft's info page on common assembly attributes: https://docs.microsoft.com/en-us/dotnet/standard/assembly/set-attributes

**Review by ljoonal — APPROVED** [review]

**Pull request merged**
