### PR TITLE
Add HeadlessCurbYourUndoManager v1.0.4

### PR DESCRIPTION
**Pull request by Nytra**

### CODE REVIEW

**Review by XDelta — COMMENTED** [review]
Is there a functional reason to respawn all the users? https://github.com/Nytra/NeosHeadlessCurbYourUndoManager/blob/master/HeadlessCurbYourUndoManager/HeadlessCurbYourUndoManager.cs#L51-L55 
Seems potentially more destructive than necessary

**Comment by Nytra** [comment]
If you don't respawn after the UndoManager component gets destroyed then undo functionality will still be broken. This is fine because the only time the mod should run that code is after the very first user joins the session. At this point nobody will be working on anything so it should be fine right?

**Comment by EIA485** [comment]
my concern is that a user could accidentally trigger this and cause people to lose work or even just confuse people as to why they were re-spawned. 
im curios what root cause of this issue is.
since this is a host only mod a different approach could be to prevent any extra UndoManagers from even initializing or syncing to anyone.

**Comment by Nytra** [comment]
Well the issue is that when a user joins the headless they sometimes attach an UndoManager in the world which shouldn't happen. I believe this UndoManager will have the joining user as its allocating user. So I think the only way to fix this properly would be to patch everyone's game to stop them from attaching it in the first place. This obviously is not possible so the next best thing is a workaround.

As for a user accidentally triggering this, it could happen if they spawn an exact copy of the default UndoManager slot from their inventory into the world root. 

There are some extra precautions I could add to this mod, like making it run only the destroy code only one time when the first user joins.

**Comment by Nytra** [comment]
@EIA485 I updated the mod to add extra precautions to prevent accidental triggering and also make the mod disable itself when it isn't needed anymore.

**Review by EIA485 — DISMISSED** [review]
not sure why your comparing users by reference id, seems fine overall.
would be nice if `AssemblyCompany` was not a blank string
`AssemblyFileVersion` and `AssemblyVersion` are "1.0.2" and "1.0.2.0"

**Comment by Nytra** [comment]
Fixed AssemblyInfo

**Review by EIA485 — DISMISSED** [review]

**Review by XDelta — APPROVED** [review]

**Pull request merged**
