### PR TITLE
Add AccessibleFullBodyCalibrator v1.0.1

### PR DESCRIPTION
**Pull request by Nytra**

### CODE REVIEW

**Review by EIA485 — CHANGES_REQUESTED** [review]
i approve of the code in f27fc36fd4f93f9ea38b843c0cc300215dd5bf9496d15406b20b39f7187aebf0 but do not think it fits into the general ui tweaks category

**Comment by Nytra** [comment]
It does tweak a UI. Do you think that the Misc category would be better?

**Comment by EIA485** [comment]
ive realized that our manifest needs some organization passes so ive created #327 as a first step.
for now the best category for this mod is probably misc

**Comment by Nytra** [comment]
Category changed to Misc

**Review by EIA485 — APPROVED** [review]

**Comment by EIA485** [comment]
looks like merging #316 created conflicts with this pr.

**Review by XDelta — APPROVED** [review]
hash still same as what @EIA485 approved, re-approving resolved conflict

**Pull request merged**
