### PR TITLE
Add filename validation

### PR DESCRIPTION
**Pull request by hazre**
Adds a regex pattern for valid filenames in the schema.

pattern: `^[^\s]+\.[A-Za-z]+$`

Here's the breakdown of the regex pattern:

- `^` matches the start of the string
- `[^\s]+` matches one or more characters that are not whitespace (i.e., spaces, tabs, newlines)
- `\.` matches a period
- `[A-Za-z]+` matches one or more letters, either uppercase or lowercase
- `$` matches the end of the string

Originally I noticed this when using my mod manager, since I don't have validation for whitespace.

for example: https://github.com/neos-modding-group/neos-mod-manifest/blob/7f041573dbaa1c36644866ea67a9410f318c0bb3/manifest.json#L2667

### CODE REVIEW

**Comment by EIA485** [comment]
i dont think we should require artifacts's names to having file extensions and no whitespace. whats the problem your trying to solve with this pr?

**Comment by zkxs** [comment]
It looks like the issue is that the filename `"ScreenDashFixer.dll "` made it into the manifest. Notice the trailing space. I think this regex is overly strict, though.

What about something like this? `^[^\s].*[^\s]$|^[^\s]$` ([explained](https://regexper.com/#%5E%5B%5E%5Cs%5D.*%5B%5E%5Cs%5D%24%7C%5E%5B%5E%5Cs%5D%24))

**Comment by hazre** [comment]
Yeah my main issue is with trailing whitespaces, adding some kind of regex can avoid that. I mainly made the extension end a bit more strict since that's what windows supports but that can be adjusted.

**Comment by EIA485** [comment]
looks good, solution looks good to me. all that needs to be done now is making this pr pass the checks

**Comment by zkxs** [comment]
> I mainly made the extension end a bit more strict since that's what windows supports but that can be adjusted.

Windows supports extensionless files, they're just uncommon. Plus, the schema should be able to support Linux-only mods, so we shouldn't impose Windows-specific character restrictions.

If you re-add the trailing newline to schema.json and fix the `"ScreenDashFixer.dll "` mistake in manifest.json, then the tests should pass and this PR should be good to go.

**Comment by ljoonal** [comment]
> so we shouldn't impose Windows-specific character restrictions.

To be pedantic, pretty sure filenames ending in white space would be valid on linux at least ;P
But I do agree wit the point that for sanity's sake we should limit them from the start/end.
I think that we should additionally ban `/` and `\`, but other than that I don't see why impose other limits.

**Review by zkxs — APPROVED** [review]

**Pull request merged**
