### PR TITLE
Add NeosModLoader versions up to current

### PR DESCRIPTION
**Pull request by XDelta**

### CODE REVIEW

**Comment by EIA485** [comment]
hmm, who can review this without being potentially biassed? all of the reviewers have contributed to nml

**Comment by XDelta** [comment]
I can split it up or we can require multiple approvals. Seems like we'd need some process for reviewing nml anyway as all the reviewers are likely going to be interacting with / contributing to nml.

**Comment by EIA485** [comment]
requiring multiple reviews seems like a good compromise to me

**Comment by ljoonal** [comment]
> hmm, who can review this without being potentially biassed? all of the reviewers have contributed to nml

I don't think having contributed to NML is a reason to not be able to review this. The only person I would dismiss reviewing it is @zkxs because they built the binaries Since I don't think reviewing NML is really about "check what the DLL does" as that's already tracked by NML's issue tracker & the community as a whole has accepted NML as safe, but mostly just "did runtime add sussy local additions to the compiled things"

**Review by ljoonal — APPROVED** [review]
All of the hashes match.

I'm too lazy to properly review them, but my vote goes to approving these since @zkxs & the NML DLLs already are and have been trusted by a lot of people anyways. I don't think MelonLoader assemblies get any sorta verification either, it's more of a "if they ever get caught doing sussy stuff the whole reputation will be gone and nobody will use it anymore" kinda of a thing.

**Comment by XDelta** [comment]
I agree with LJ with really as long as it is looked over by not the person who compiled the final binaries it should be fine.

**Pull request merged**
