### PR TITLE
add HeadlessTweaks

### PR DESCRIPTION
**Pull request by EIA485**

### CODE REVIEW

**Review by ljoonal — CHANGES_REQUESTED** [review]
Requested changes: I think this should have `Discord.Net.Webhook` and `Discord.Net.Core` as dependencies (similar to how NML depends on harmony).

Other than that, the mod contains quite a bit of code that on some level deals with network requests, which is always a tad sus. I'd like it if multiple people could independently review that this is safe due to it.

Other notes:
- `HelperExtensions.cs#24` contains hardcoded neosdb url.
- `MessageCommands.cs` is very long, haven't fully reviewed it.
- `NewHeadlessCommands.cs` is hard for me to review due to the deassembly coming out nasty since I don't have headless client references so it's just IL partially
- The notes are only about v1.1.0, I don't think we should even bother adding 1.0.0 since it's just more to review for no reason.

**Comment by EIA485** [comment]
setting this pr to a draft while we wait for the mod creator to provide artifacts of the dependencies. the dependencies don't provide compiled binaries.

**Comment by ljoonal** [comment]
We could add the dependencies and just not have the artifact URLs/releases for the defined deps. That way if there's a mod manager, they could show the dependency but I just couldn't download/install it.

**Comment by ljoonal** [comment]
Don't think it's reasonable to review the Discord.NET dll files, so need to somehow verify that the hashes match to the official releases.

**Comment by EIA485** [comment]
maybe we can ask the mod dev to build those libraries in reproducible build mode so you can validate that the source matches the binary

**Comment by ljoonal** [comment]
Closing this in favor of #104

**Pull request closed without merging**
