### PR TITLE
Add AudioClipWizard v1.0.0

### PR DESCRIPTION
**Pull request by Nytra**

### CODE REVIEW

**Review by EIA485 — DISMISSED** [review]

**Comment by EIA485** [comment]
since i already approved hash f846d313facedc1115da8ff492c56ab9cf152d8eedc017f3334cfb8128807f47 you can add version 1.0.1 instead of replacing 1.0.0 with it. the reason i did not merge this is because there are conflicts that need manual resolving. maybe pr version 1.0.1 separately so a different reviewer can approve that one.

**Comment by Nytra** [comment]
But the only changes in v1.0.1 are the ones from your PR and a version number bump

**Comment by Nytra** [comment]
However I will revert back to v1.0.0 if you would like

**Comment by EIA485** [comment]
for this pr revert to 1.0.0 and resolve conflicts. so i can merge it. after feel free to create a second pr for 1.0.1. i cant merge my own changes...

**Comment by Nytra** [comment]
Reverted to v1.0.0

**Comment by Nytra** [comment]
I don't know how to resolve conflicts though :/

**Comment by EIA485** [comment]
version entry is still 1.0.1
one way to resolve conflicts is through the github web ui. on this page there is a button that says `resolve conflicts` pressing this will open a web editor where you can resolve the conflicts by fixing the overlapping json.

**Comment by Nytra** [comment]
Resolved conflicts. Hopefully I did it right :)

**Review by EIA485 — APPROVED** [review]

**Comment by EIA485** [comment]
yep, perfect. sorry for all the hassle.

**Pull request merged**
