### PR TITLE
recagorized some entries

### PR DESCRIPTION
**Pull request by EIA485**
the `General UI Tweaks` category could be removed completely if reviews deemed necessary by moving NeosBetterIMESupport into Bug Workarounds and by moving ReduceAnimation and SquishPanels into Visual Tweaks

maybe a `notifications` category should be created, by my count there are 5 entries that would go under that.

### CODE REVIEW

**Comment by XDelta** [comment]
`General UI Tweaks` feels like they all can fit within `Visual Tweaks` or `Dash Tweaks` if not a different category entirely

**Comment by EIA485** [comment]
the original idea was mods that affect ui widely

**Comment by XDelta** [comment]
It does seem to be one of a few categories that isn't as well defined on https://www.neosmodloader.com/categories almost making it harder to categorize when a mod feels like it falls on a few categories at the same time.

**Comment by XDelta** [comment]
At the moment notification mods are probably fine to stay under dash tweaks.

**Comment by EIA485** [comment]
this is a good state for now. changes can always be made later.

**Comment by XDelta** [comment]
Note to also update the categories page on the website to reflect this change.

**Review by XDelta — APPROVED** [review]

**Pull request merged**
