### PR TITLE
Add PresenceToggle

### PR DESCRIPTION
**Pull request by art0007i**

### CODE REVIEW

**Comment by EIA485** [comment]
repo does not exist, i assume its private

**Comment by art0007i** [comment]
yeah it was private by accident, fixed now

**Review by EIA485 — APPROVED** [review]
built in debug mode

**Comment by EIA485** [comment]
@art0007i feel free to merge, just leaving it open in-case you want to make a non debug build

**Comment by art0007i** [comment]
I don't have the option to merge

**Pull request merged**
