### PR TITLE
Add new release and deprecate old ones

### PR DESCRIPTION
**Pull request by Banane9**
Title

### CODE REVIEW

**Comment by XDelta** [comment]
Deprecating older versions of mods isn't needed if you are continuing to update the mod itself.

**Comment by XDelta** [comment]
Additionally noticed you put marked the latest version of https://github.com/Banane9/NeosAvatarClothingHelper/ as deprecated. If you are no longer supporting that mod, the flag should be on the top level of the mod to cover all versions.

**Comment by Banane9** [comment]
> Deprecating older versions of mods isn't needed if you are continuing to update the mod itself.

Hmmm, just saw someone else did that too, and it seems reasonable to distinguish which versions are still supported.



> Additionally noticed you put marked the latest version of https://github.com/Banane9/NeosAvatarClothingHelper/ as deprecated.

Oops, that was a mistake.

**Comment by ljoonal** [comment]
> it seems reasonable to distinguish which versions are still supported.

I don't see why the assumption to this wouldn't always just be "only the latest". While technically yeah you could have multiple versions you support (legacy / new beta / etc), I don't think that it's sensible to require marking old mod versions as deprecated always...

**Comment by Banane9** [comment]
New mod added, who dis

**Review by XDelta — APPROVED** [review]

**Pull request merged**
