### PR TITLE
Add EnumDropdown v1.2.0

### PR DESCRIPTION
**Pull request by badhaloninja**

### CODE REVIEW

**Comment by Banane9** [comment]
Hold on with this, I still need to PR you an addition :'D

**Comment by EIA485** [comment]
i cant approve this since i contributed to this version. the `NeosMod` version is 1.1.0

**Comment by badhaloninja** [comment]
Oops I missed that, fixed now

**Comment by Banane9** [comment]
@badhaloninja check the prs on it too 👀

**Review by XDelta — APPROVED** [review]

**Pull request merged**
