### PR TITLE
fixes #200

### LINKED ISSUE #200: The discord notification workflow fails on single quote in mod description
https://github.com/neos-modding-group/neos-mod-manifest/actions/runs/3790202585/jobs/6444641922#step:6:1
https://github.com/neos-modding-group/neos-mod-manifest/actions/runs/3577158302/jobs/6015832575

basically the action calls curl with some data like

```bash
curl -d '{"description":"you're"}' '***'
```

which crashes because of the single quote inside the word "you're" ends the data part of the request specified by the -d flag

I think to fix this it would be as simple as replacing all `'` with `'\''` which seems to be the escape character for quotes in bash

### PR DESCRIPTION
**Pull request by EIA485**

### CODE REVIEW

**Review by XDelta — APPROVED** [review]

**Review by XDelta — APPROVED** [review]

**Comment by EIA485** [comment]
huh, guess github decided to auto close this issue, i reran the failed action for #198 and it failed. not sure why #200 did not fix the issue

**Comment by art0007i** [comment]
@XDelta  @EIA485 what the fuck?? did any of you even try to test this change????? im sorry but just merging this code which at best does nothing and at worst actually crashes the workflow on every run is a pretty bad choice in my opinion

python's replace function does not modify the original string so it doesn't make sense to use str.replace while discarding the returned value

also the escape for single quotes (`'`) in bash, as mentioned in #200 uses `'\''` to NOT `\'`

**Comment by EIA485** [comment]
@art0007i 
not sure how  to test github actions locally

**Comment by art0007i** [comment]
You can just run the same commands as the action in your shell, action uses a simple linux shell and it just runs simple commands, can just copy paste them.
Yolo test in prod is terrible, don't do it!
Or at least this big of a yolo test, the 2 issues I've noted were the first 2 I noticed without even seeing the full python file, later I also found that your code only iterates over the dictionary KEYS so it would still do nothing even if the other 2 issues were fixed.

**Comment by art0007i** [comment]
if you want to run actions locally after a really quick google search I found this as well https://github.com/nektos/act

**Pull request merged**
