### PR TITLE
docs: add JworksNeosFixFrickenSync mod info

### PR DESCRIPTION
**Pull request by stiefeljackal**
Added mod JworksNeosFixFrickenSync info into the manifest.

EDITED: Removed checklist. Don't know why PR was saved with that, or I might've been too tired when posting...

### CODE REVIEW

**Comment by stiefeljackal** [comment]
Added version 1.1.0 to the manifest as well. Added the deprecated flag to version 1.0.0.

**Comment by XDelta** [comment]
Deprecating individual mod versions isn't needed in most cases, also you can remove the 1.0.0 as you have added a later version before it was reviewed.

**Comment by XDelta** [comment]
NeosMod.Link is a 404 pointing towards stiefeljackal/NeosFixFrickenSync

**Comment by stiefeljackal** [comment]
@XDelta Thank you for pointing that out. I fixed NeosMod.Link with the correct URL and recompiled the DLL. Release page was updated with newer DLL and new SHA256. Manifest was updated to remove 1.0.0 and to update the SHA256 on 1.1.0.

**Comment by stiefeljackal** [comment]
Hey @XDelta. I'm just curious if there is any updates to this. I have addressed the error that you noted in your last comment.

**Review by XDelta — APPROVED** [review]
Sorry for the delay, I've been pretty busy.
Didn't run it myself to check but it looks like `LogUploadUpdate` would be somwhat log spammy if it is logging every time the progress changes, probably better for a Debug log. Otherwise looks fine.

**Comment by stiefeljackal** [comment]
No problem about the delay! 

I will see what I can do to limit the logging for that particular event when I release v2.0.0 of this mod.

Thank you for your approval!

**Pull request merged**
