### PR TITLE
Add WorldListSessionHider v1.1.0

### PR DESCRIPTION
**Pull request by Nytra**

### CODE REVIEW

**Review by EIA485 — CHANGES_REQUESTED** [review]
`neosmod` version is 1.0.0 for d22ee06406ffd0670f5a3a254fefabde9e4860aaa05d477c2b0078e879fa5c93

**Comment by Nytra** [comment]
Fixed

**Review by EIA485 — APPROVED** [review]
some performance optimizations could be made but this code is not evil

**Comment by Nytra** [comment]
What performance optimizations could be made? I'm curious.

**Pull request merged**
