### PR TITLE
Add LocalStorage 1.1.0

### PR DESCRIPTION
**Pull request by XDelta**

### CODE REVIEW

**Comment by XDelta** [comment]
Set the category to Dash Tweaks, seems like the closest, feel free to suggest a different category.

**Comment by art0007i** [comment]
I specifically didn't put it in the manifest cuz it's kinda jank, but maybe it's fine to go in there now that some time has passed and it hasn't had any major issues yet, would definitely prefer it with some kind of "experimental" flag or warning of some sort that says it's not a perfect solution (it's far from it)

the mod is more useful for peeking at the internal structure of saved items rather than actually keeping items there as a secondary inventory (at least that's how I used it, and I could see potential issues with trying to use it as a more permanent storage method)

**Comment by XDelta** [comment]
Should we add a new flag for experimental or have it as an experimental category (which would be already listed separately on the website)?

**Comment by EIA485** [comment]
it should be a flag, that way pre release versions can be marked as such but future versions will be in the correct category

**Comment by XDelta** [comment]
would now need small changes to the validation json. or treat it more as a prerelease (with prerelease flag) instead (on manifest but not included on nml mod page)

**Comment by ljoonal** [comment]
> would now need small changes to the validation json. or treat it more as a prerelease (with prerelease flag) instead (on manifest but not included on nml mod page)

That should be done instead of a new flag, as this is exactly what that flag is for according to the website docs:

> `prerelease` Mod dev wants to limit distribution

**Comment by EIA485** [comment]
probably fits better as a technical tweak since it can be accessed externally to the dash

**Comment by EIA485** [comment]
lets reopen this under a branch in this repo

**Pull request closed without merging**
